builds:
  - goos:
      - windows
    ldflags:
      - -H=windowsgui
archives:
- format: binary
  name_template: "{{ .ProjectName }}-{{ .Arch }}-v{{.Version}}"
  replacements:
    386: x86
    amd64: x64